# Generated by Django 2.1.7 on 2019-03-12 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartParkingServer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Favourite_parking_lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Old_capacity_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parkedCars', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parkin_lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('capacity', models.IntegerField()),
                ('actualParkedCars', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=100)),
                ('parkingLotID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartParkingServer.Parkin_lot')),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('countryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartParkingServer.Country')),
            ],
        ),
        migrations.AddField(
            model_name='parkin_lot',
            name='townID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartParkingServer.Town'),
        ),
        migrations.AddField(
            model_name='old_capacity_data',
            name='parkingLotID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartParkingServer.Parkin_lot'),
        ),
        migrations.AddField(
            model_name='favourite_parking_lot',
            name='parkingLotID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartParkingServer.Parkin_lot'),
        ),
        migrations.AddField(
            model_name='favourite_parking_lot',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartParkingServer.User'),
        ),
    ]
