# Generated by Django 2.1.7 on 2019-03-13 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartParkingServer', '0002_auto_20190312_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite_parking_lot',
            old_name='parkingLotID',
            new_name='parkinglot',
        ),
        migrations.RenameField(
            model_name='favourite_parking_lot',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='old_capacity_data',
            old_name='parkedCars',
            new_name='parkedcars',
        ),
        migrations.RenameField(
            model_name='old_capacity_data',
            old_name='parkingLotID',
            new_name='parkinglot',
        ),
        migrations.RenameField(
            model_name='parkin_lot',
            old_name='actualParkedCars',
            new_name='actualparkedcars',
        ),
        migrations.RenameField(
            model_name='parkin_lot',
            old_name='townID',
            new_name='town',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='parkingLotID',
            new_name='parkinglot',
        ),
        migrations.RenameField(
            model_name='town',
            old_name='countryID',
            new_name='country',
        ),
    ]
