# Generated by Django 2.1.7 on 2019-03-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartParkingServer', '0003_auto_20190313_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkin_lot',
            name='actualparkedcars',
            field=models.IntegerField(null=True),
        ),
    ]
