# Generated by Django 2.1.7 on 2019-03-31 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartParkingServer', '0006_auto_20190320_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite_parking_lot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
