# Generated by Django 2.1.7 on 2019-04-20 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartParkingServer', '0010_auto_20190403_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite_parking_lot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
