# Generated by Django 2.1.7 on 2019-04-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartParkingServer', '0015_auto_20190421_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.TextField(),
        ),
    ]
